# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pos_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mygestion
      MYSQL_ROOT_PASSWORD: hygro8714
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DB_Mygestion.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: ./backend
    container_name: pos_django_api
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /mnt/c/Documentos:/documentos_json
    # CAMBIO AQUÍ: Exponemos el 8001 hacia afuera, apuntando al 8000 de adentro
    ports:
      - "0.0.0.0:8001:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=mygestion
      - DB_USER=root
      - DB_PASS=hygro8714

  redis:
    image: redis:alpine
    container_name: pos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"


  frontend:
    build: ./frontend
    container_name: pos_react_front
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true           
    # AGREGAMOS --host para que Vite escuche las peticiones de Docker
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Esto es clave para no pisar los módulos con los de Windows
    depends_on:
      - web

volumes:
  db_data: