# Generated by Django 4.2.30 on 2026-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('cod_art', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rubro', models.CharField(blank=True, max_length=4, null=True)),
                ('subrubro', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('costo_ult', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('costo_pond', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('stock_min', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('stock_max', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('stock_ini', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('stock_ini_fec', models.DateTimeField(blank=True, null=True)),
                ('precio_1', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_3', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_4', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_5', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_6', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_7', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_8', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_9', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_10', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_11', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_12', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=5, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ult_compra', models.DateTimeField(blank=True, null=True)),
                ('ult_venta', models.DateTimeField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=3, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('artic_prov', models.CharField(blank=True, max_length=16, null=True)),
                ('artic_obs', models.CharField(blank=True, max_length=250, null=True)),
                ('noactualiza', models.IntegerField(blank=True, null=True)),
                ('modifica_uni', models.IntegerField(blank=True, null=True)),
                ('moneda', models.SmallIntegerField(blank=True, null=True)),
                ('libre', models.SmallIntegerField(blank=True, null=True)),
                ('padre1_hijo2', models.IntegerField(blank=True, null=True)),
                ('es_combo', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_mod', models.DateTimeField(blank=True, null=True)),
                ('barra', models.CharField(blank=True, max_length=50, null=True)),
                ('impuesto_ng', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido_multiplo', models.IntegerField(blank=True, null=True)),
                ('pedido_estado_inventario', models.IntegerField(blank=True, null=True)),
                ('existe_en_algun_kit', models.IntegerField(blank=True, null=True)),
                ('clase', models.CharField(blank=True, max_length=3, null=True)),
                ('existe_en_alguna_promo', models.IntegerField(blank=True, null=True)),
                ('ultima_actu_precio', models.DateTimeField(blank=True, null=True)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad2', models.CharField(blank=True, max_length=3, null=True)),
                ('factor_conv', models.FloatField(blank=True, null=True)),
                ('p5329', models.IntegerField(blank=True, null=True)),
                ('iva7', models.IntegerField(blank=True, null=True)),
                ('piva7', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cant_limi_mayo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uniporbulto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
