# Generated by Django 4.2.30 on 2026-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'managed': False},
        ),
    ]
