# Generated by Django 4.2.30 on 2026-05-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_articulosbom_articulosestadoinventario_articulosivas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpExportacionAplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicativo', models.CharField(choices=[('SICORE', 'SICORE — Retenciones/Percepciones AFIP'), ('SIFERE', 'SIFERE — IIBB Convenio Multilateral'), ('SIACER', 'SIACER — IIBB Entre Ríos'), ('EARCIBA', 'e-ARCIBA — IIBB CABA'), ('SICOL', 'SICOL — Retenciones AFIP'), ('REGELEC', 'Reg. Electrónica AFIP'), ('DUPELEC', 'Duplicados Electrónicos CAE/CAEA'), ('SIRFT', 'SIRFT — IIBB Santa Fe (AFIP/Batres)'), ('ARBA', 'ARBA A122R — IIBB Buenos Aires'), ('SIJP', 'SIJP — Jubilaciones AFIP'), ('SVINCUL', 'Sujetos Vinculados AFIP'), ('SIRE', 'SIRE — Retenciones AFIP'), ('F8001', 'RG 3668 F8001 — Facturas M'), ('SIRCAR', 'SIRCAR — IIBB Córdoba'), ('SIPRIB', 'SIPRIB — IIBB Santa Fe DGR'), ('ITC', 'ITC — Impuesto Transferencia Combustibles')], max_length=10)),
                ('circuito', models.CharField(choices=[('V', 'Ventas'), ('C', 'Compras'), ('A', 'Ambos')], default='V', max_length=1)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=200)),
                ('contenido_b64', models.TextField(blank=True, default='', help_text='Contenido del archivo en base64 para descarga')),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.CharField(blank=True, default='', max_length=20)),
                ('cantidad_registros', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'imp_exportaciones_aplicativos',
                'ordering': ['-generado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImpPuntoRegistracion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'imp_puntos_registracion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ImpRegimenEspecial',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SICORE', 'SICORE'), ('SIFERE', 'SIFERE'), ('OTRO', 'Otro')], default='SICORE', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'imp_regimenes_especiales',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ImpLibroIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(choices=[('V', 'Ventas'), ('C', 'Compras')], max_length=1)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('P', 'Provisorio'), ('D', 'Definitivo')], default='P', max_length=1)),
                ('primer_numero', models.IntegerField(default=1)),
                ('mostrar_cert_ret', models.BooleanField(default=False)),
                ('mostrar_iibb', models.BooleanField(default=True)),
                ('mostrar_comp_b_agrup', models.BooleanField(default=False)),
                ('mostrar_anulados_agrup', models.BooleanField(default=False)),
                ('margen_superior', models.BooleanField(default=False)),
                ('lineas_separadoras', models.BooleanField(default=True)),
                ('imprime_encabezado', models.BooleanField(default=False)),
                ('texto_encabezado', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(blank=True, default='', max_length=20)),
                ('punto_registracion', models.ForeignKey(blank=True, db_column='punto_registracion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.imppuntoregistracion')),
            ],
            options={
                'db_table': 'imp_libros_iva',
                'ordering': ['-fecha_desde', 'circuito'],
            },
        ),
        migrations.CreateModel(
            name='ImpDeclaracionJurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes del período')),
                ('version', models.CharField(choices=[('V1', 'R.C. 3685 (R.G. 715/99)'), ('V2', 'IVA Estándar')], default='V2', max_length=2)),
                ('tipo_emision', models.CharField(choices=[('O', 'Original'), ('R1', 'Rectificativa N° 1'), ('R2', 'Rectificativa N° 2'), ('R3', 'Rectificativa N° 3')], default='O', max_length=2)),
                ('pasado_cg', models.BooleanField(default=False, help_text='Si fue trasladado a Contabilidad General')),
                ('total_debito_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credito_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'imp_declaraciones_juradas',
                'ordering': ['-periodo', 'version'],
                'unique_together': {('periodo', 'version', 'tipo_emision')},
            },
        ),
    ]
