# Generated by Django 4.2.30 on 2026-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_bodcontratouva_boddeclaracioninv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impdeclaracionjurada',
            name='emitido_por',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='impexportacionaplicativo',
            name='aplicativo',
            field=models.CharField(choices=[('SICORE', 'SICORE — Retenciones/Percepciones ARCA'), ('SIFERE', 'SIFERE — IIBB Convenio Multilateral'), ('SIACER', 'SIACER — IIBB Entre Ríos'), ('EARCIBA', 'e-ARCIBA — IIBB CABA'), ('SICOL', 'SICOL — Retenciones ARCA'), ('REGELEC', 'Reg. Electrónica ARCA'), ('DUPELEC', 'Duplicados Electrónicos CAE/CAEA'), ('SIRFT', 'SIRFT — IIBB Santa Fe'), ('ARBA', 'ARBA A122R — IIBB Buenos Aires'), ('SIJP', 'SIJP — Jubilaciones ARCA'), ('SVINCUL', 'Sujetos Vinculados ARCA'), ('SIRE', 'SIRE — Retenciones ARCA'), ('F8001', 'RG 3668 F8001 — Facturas M'), ('SIRCAR', 'SIRCAR — IIBB Córdoba'), ('SIPRIB', 'SIPRIB — IIBB Santa Fe DGR'), ('ITC', 'ITC — Impuesto Transferencia Combustibles')], max_length=10),
        ),
        migrations.AlterField(
            model_name='impexportacionaplicativo',
            name='generado_por',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='implibroiva',
            name='creado_por',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
