# Generated by Django 4.2.30 on 2026-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_sprint1_impositivo_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpIVAAlicuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movim', models.BigIntegerField()),
                ('circuito', models.CharField(choices=[('V', 'Ventas'), ('C', 'Compras')], max_length=1)),
                ('alicuota', models.DecimalField(decimal_places=2, help_text='Porcentaje: 21.00, 10.50, 27.00, 5.00, 2.50, 0.00', max_digits=5)),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=0, help_text='Base imponible para esta alícuota (sin IVA).', max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='Importe de IVA correspondiente a esta alícuota.', max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'imp_iva_alicuotas',
                'ordering': ['circuito', 'movim', 'alicuota'],
                'indexes': [models.Index(fields=['circuito', 'movim'], name='iva_alic_circ_mov_idx'), models.Index(fields=['circuito', 'alicuota'], name='iva_alic_circ_ali_idx')],
                'unique_together': {('movim', 'circuito', 'alicuota')},
            },
        ),
    ]
